### ISSUE TITLE
get records based on modified time

### ISSUE THREAD

**Issue by ManasaVijayaBhaskar** [cvengros/salesforce_bulk_query#16]
is it possible to get the records that were modified after a certain time??

**Comment by cvengros** [comment]
Hi @ManasaVijayaBhaskar, in the new version you can use the :date_field parameter to filter on a date field available on the Salesforce object, including system fields, like LastModifiedDate or SystemModstamp. So using the :date_field and :date_from parameters you can download just records modified after a given date. See this test for example usage: https://github.com/cvengros/salesforce_bulk_query/blob/master/spec/salesforce_bulk_query_spec.rb#L108

**Comment by ManasaVijayaBhaskar** [comment]
@cvengros thank you

one more question, do you have plans of implementing 'where' clause?

**Comment by cvengros** [comment]
It's not my priority now. Feel free to contribute: https://github.com/cvengros/salesforce_bulk_query/blob/master/README.md#contributing
